title: Nxh
description: Hello Wolrd.!
theme: just-the-docs
domain: 2nxh.com
url: https://2nxh.com
kramdown:
  math_engine: null

# Google Analytics Tracking
ga_tracking: G-JNHS6T6WT2
ga_tracking_anonymize_ip: true
